apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: https://prometheus.gentleflower-99ef02e0.eastus.azurecontainerapps.io:443
    isDefault: true
    editable: true
