const TeamIcons = [
  {
    id: "team_icons",
    name: "Team Icons",
    emojis: [
      "ph:coffee-bean-duotone",
      "ph:apple-logo-duotone",
      "ph:airplane-duotone",
      "ph:acorn-duotone",
      "ph:android-logo-duotone",
      "ph:atom-duotone",
      "ph:bell-duotone",
      "ph:battery-vertical-full-duotone",
      "ph:book-open-text-duotone",
      "ph:briefcase-duotone",
      "ph:butterfly-duotone",
      "ph:cable-car-duotone",
      "ph:call-bell-duotone",
      "ph:car-duotone",
      "ph:castle-turret-duotone",
      "ph:chart-donut-duotone",
      "ph:church-duotone",
      "ph:clipboard-text-duotone",
      "ph:club-duotone",
      "ph:command-duotone",
      "ph:cpu-duotone",
      "ph:currency-circle-dollar-duotone",
      "ph:dev-to-logo-duotone",
      "ph:dribbble-logo-duotone",
      "ph:fan-duotone",
      "ph:fire-truck-duotone",
      "ph:flying-saucer-duotone",
      "ph:hand-soap-duotone",
      "ph:headset-duotone",
      "ph:hurricane-duotone",
      "ph:laptop-duotone",
      "ph:notepad-duotone",
      "ph:nut-duotone",
      "ph:peace-duotone",
      "ph:poker-chip-duotone",
      "ph:road-horizon-duotone",
      "ph:shield-check-duotone",
      "ph:slack-logo-duotone",
      "ph:squares-four-duotone",
      "ph:swatches-duotone",
      "ph:tipi-duotone",
      "ph:train-duotone",
      "ph:video-duotone",
      "ph:windows-logo-duotone",
    ].map((icon) => ({
      id: icon,
      skins: [
        {
          src: `https://api.iconify.design/${icon}.svg?color=%232065d1&width=75&height=75'`,
        },
      ],
    })),
  },
];

export default TeamIcons;
